# Generated by Django 6.1.1 on 2026-09-19 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_task_completed_at_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='generated_from',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_occurrence', to='chores.task'),
        ),
    ]
